### ISSUE TITLE
Does not clear diagnostics for files with no problems

### ISSUE THREAD

**Issue by jbachhardie** [flowtype/flow-language-server#64]
According to the LSP

>When a file changes it is the server's responsibility to re-compute diagnostics and push them to the client. If the computed set is empty it has to push the empty array to clear former diagnostics.

But it seems, from my attempts to get this integrated with vscode and looking at the source, that the Flow LS doesn't send anything at all for files that have no problems, leading to diagnostics not being cleared at least in the default vscode client implementation.

**Comment by wbinnssmith** [comment]
This should be addressed in 0.4. Thanks for the report!

**Comment by jbachhardie** [comment]
This is not quite addressed, unfortunately. When the project as a whole goes from some to 0 problems then  the empty diagnostics array is pushed but when a given *file* within the project goes from some to 0 problems but problems still exist in other files an empty array is not pushed for that file, causing those problems to not be cleared until restart.

Looking at the code this seems to be because the empty check is done on the diagnostics object as a whole, not per file that has previously been reported as having problems.
